# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b692dc0ff4b59d4efbc7333d464db622328ee80d52a7c5fb3c96c7a86a997aea9291619af7a3bd415379d96937a09f5262def3940598ab6ec4edff757f82a484

test:
  secret_key_base: 6605338b7e4c6a8b7887f9ff9688284d5a3824406b53f793a5b219d1bd4c178d644bc23172cb50e3709526c401e60656582c44fe8722c566ce632376ffcf8bf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
